name: "git-identity"
description: "A GitHub Action to set git identity"
author: "Jeremie Drouet <jeremie.drouet@gmail.com>"

branding:
  icon: "heart"
  color: "red"

inputs:
  username:
    description: "name of the user"
    required: false
    default: "github-actions[bot]"

runs:
  using: composite
  steps:
    - name: globally set user name
      shell: bash
      run: git config user.name "${{ inputs.username }}"
    - name: set user email
      shell: bash
      run: git config user.email "$GITHUB_ACTOR_ID+$GITHUB_ACTOR@users.noreply.github.com"
